# -*- coding: utf-8 -*-
"""Answer_Script (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tgbAU3D4tJ8h0v2AwMFzVwJU6TURdAYb
"""

#pip install openai

"""### fl problem =" "  (Line 4)  hot probleme mt3k w runi """


def answer(problem):
  import openai
  openai.api_key = "sk-"
  #problem="The biking club has a goal to ride 874 miles in one month.The have biked 292 miles so far.How many more miles do they have left?"
  solution="just the right answer of this without explication" +problem

  completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo", 
    messages=[{"role": "user", "content": problem}]
  )

  completion2 = openai.ChatCompletion.create(
    model="gpt-3.5-turbo", 
    messages=[{"role": "user", "content": solution}]
  )

  print(completion['choices'][0]['message']['content'])#explication chnawa openAI y5rj
  print("---------------------------------------------")
  print(completion2['choices'][0]['message']['content'])#juste e reponse
  txt1=completion['choices'][0]['message']['content']
  txt2=completion2['choices'][0]['message']['content']
  return txt1,txt2 

def remove_period(text):
    if text.endswith("."):
        return text[:-1]
    else:
        return text
    
def answer2(problem):
  import openai

  openai.api_key = "import openai"

  openai.api_key = "sk-"

 # Define the problem prompt
  #prompt = "The biking club has a goal to ride 874 miles in one month. They have biked 292 miles so far. How many more miles do they have left?"
  solution="just the right answer of this without explication" + problem
  # Use the GPT-3 API to generate a solution
  completion = openai.Completion.create(
      engine="text-davinci-002",
      prompt=solution,
      max_tokens=50,
      n=1,
      stop=None,
      temperature=0.5,
  )

  # Print the generated solution
  x=remove_period(completion.choices[0].text.strip())
  return x
